library font_awesome_flutter;

import 'package:flutter/widgets.dart';
import 'package:font_awesome_flutter/src/icon_data.dart';
export 'package:font_awesome_flutter/src/fa_icon.dart';
export 'package:font_awesome_flutter/src/icon_data.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!

/// Icons based on font awesome 6.5.1
@staticIconProvider
class FontAwesomeIcons {
  /// Regular Address Book icon
  ///
  /// https://fontawesome.com/icons/address-book?style=regular
  /// contact, directory, employee, index, little black book, portfolio, rolodex, uer, username
  static const IconData addressBook = IconDataRegular(0xf2b9);

  /// Alias contact-book for icon [addressBook]
  @Deprecated('Use "addressBook" instead.')
  static const IconData contactBook = addressBook;

  /// Regular Address Card icon
  ///
  /// https://fontawesome.com/icons/address-card?style=regular
  /// about, contact, employee, id, identification, portfolio, postcard, profile, registration, uer, username
  static const IconData addressCard = IconDataRegular(0xf2bb);

  /// Alias contact-card for icon [addressCard]
  @Deprecated('Use "addressCard" instead.')
  static const IconData contactCard = addressCard;

  /// Alias vcard for icon [addressCard]
  @Deprecated('Use "addressCard" instead.')
  static const IconData vcard = addressCard;

  /// Regular Bell icon
  ///
  /// https://fontawesome.com/icons/bell?style=regular
  /// alarm, alert, bel, bell, chime, notification, reminder, request
  static const IconData bell = IconDataRegular(0xf0f3);

  /// Regular Bell Slash icon
  ///
  /// https://fontawesome.com/icons/bell-slash?style=regular
  /// alert, bell, bell with slash, cancel, disabled, forbidden, mute, notification, off, quiet, reminder, silent
  static const IconData bellSlash = IconDataRegular(0xf1f6);

  /// Regular Bookmark icon
  ///
  /// https://fontawesome.com/icons/bookmark?style=regular
  /// bookmark, favorite, library, mark, marker, read, remember, research, save
  static const IconData bookmark = IconDataRegular(0xf02e);

  /// Regular Building icon
  ///
  /// https://fontawesome.com/icons/building?style=regular
  /// apartment, building, business, city, company, office, office building, urban, work
  static const IconData building = IconDataRegular(0xf1ad);

  /// Regular Calendar icon
  ///
  /// https://fontawesome.com/icons/calendar?style=regular
  /// calendar, calendar-o, date, day, event, month, schedule, tear-off calendar, time, when, year
  static const IconData calendar = IconDataRegular(0xf133);

  /// Regular Calendar Check icon
  ///
  /// https://fontawesome.com/icons/calendar-check?style=regular
  /// accept, agree, appointment, confirm, correct, date, day, done, enable, event, month, ok, schedule, select, success, tick, time, todo, validate, warranty, when, working, year
  static const IconData calendarCheck = IconDataRegular(0xf274);

  /// Regular Calendar Days icon
  ///
  /// https://fontawesome.com/icons/calendar-days?style=regular
  /// calendar, date, day, event, month, schedule, time, when, year
  static const IconData calendarDays = IconDataRegular(0xf073);

  /// Alias calendar-alt for icon [calendarDays]
  @Deprecated('Use "calendarDays" instead.')
  static const IconData calendarAlt = calendarDays;

  /// Regular Calendar Minus icon
  ///
  /// https://fontawesome.com/icons/calendar-minus?style=regular
  /// calendar, date, day, delete, event, month, negative, remove, schedule, time, when, year
  static const IconData calendarMinus = IconDataRegular(0xf272);

  /// Regular Calendar Plus icon
  ///
  /// https://fontawesome.com/icons/calendar-plus?style=regular
  /// add, calendar, create, date, day, event, month, new, positive, schedule, time, when, year
  static const IconData calendarPlus = IconDataRegular(0xf271);

  /// Regular Calendar Xmark icon
  ///
  /// https://fontawesome.com/icons/calendar-xmark?style=regular
  /// archive, calendar, date, day, delete, event, month, remove, schedule, time, uncheck, when, x, year
  static const IconData calendarXmark = IconDataRegular(0xf273);

  /// Alias calendar-times for icon [calendarXmark]
  @Deprecated('Use "calendarXmark" instead.')
  static const IconData calendarTimes = calendarXmark;

  /// Regular Chart Bar icon
  ///
  /// https://fontawesome.com/icons/chart-bar?style=regular
  /// analytics, bar, chart, graph, performance, statistics
  static const IconData chartBar = IconDataRegular(0xf080);

  /// Alias bar-chart for icon [chartBar]
  @Deprecated('Use "chartBar" instead.')
  static const IconData barChart = chartBar;

  /// Regular Chess Bishop icon
  ///
  /// https://fontawesome.com/icons/chess-bishop?style=regular
  /// Black Chess Bishop, board, checkmate, game, strategy
  static const IconData chessBishop = IconDataRegular(0xf43a);

  /// Regular Chess King icon
  ///
  /// https://fontawesome.com/icons/chess-king?style=regular
  /// Black Chess King, board, checkmate, game, strategy
  static const IconData chessKing = IconDataRegular(0xf43f);

  /// Regular Chess Knight icon
  ///
  /// https://fontawesome.com/icons/chess-knight?style=regular
  /// Black Chess Knight, board, checkmate, game, horse, strategy
  static const IconData chessKnight = IconDataRegular(0xf441);

  /// Regular Chess Pawn icon
  ///
  /// https://fontawesome.com/icons/chess-pawn?style=regular
  /// board, checkmate, chess, chess pawn, dupe, expendable, game, strategy
  static const IconData chessPawn = IconDataRegular(0xf443);

  /// Regular Chess Queen icon
  ///
  /// https://fontawesome.com/icons/chess-queen?style=regular
  /// Black Chess Queen, board, checkmate, game, strategy
  static const IconData chessQueen = IconDataRegular(0xf445);

  /// Regular Chess Rook icon
  ///
  /// https://fontawesome.com/icons/chess-rook?style=regular
  /// Black Chess Rook, board, castle, checkmate, game, strategy
  static const IconData chessRook = IconDataRegular(0xf447);

  /// Regular Circle icon
  ///
  /// https://fontawesome.com/icons/circle?style=regular
  /// Black Circle, Black Large Circle, black circle, blue, blue circle, brown, brown circle, chart, circle, circle-thin, diameter, dot, ellipse, fill, geometric, green, green circle, notification, orange, orange circle, progress, purple, purple circle, red, red circle, round, white circle, yellow, yellow circle
  static const IconData circle = IconDataRegular(0xf111);

  /// Regular Circle Check icon
  ///
  /// https://fontawesome.com/icons/circle-check?style=regular
  /// accept, affected, agree, clear, confirm, correct, coupon, done, enable, ok, select, success, tick, todo, validate, working, yes
  static const IconData circleCheck = IconDataRegular(0xf058);

  /// Alias check-circle for icon [circleCheck]
  @Deprecated('Use "circleCheck" instead.')
  static const IconData checkCircle = circleCheck;

  /// Regular Circle Dot icon
  ///
  /// https://fontawesome.com/icons/circle-dot?style=regular
  /// bullseye, button, geometric, notification, radio, radio button, target
  static const IconData circleDot = IconDataRegular(0xf192);

  /// Alias dot-circle for icon [circleDot]
  @Deprecated('Use "circleDot" instead.')
  static const IconData dotCircle = circleDot;

  /// Regular Circle Down icon
  ///
  /// https://fontawesome.com/icons/circle-down?style=regular
  /// arrow-circle-o-down, download
  static const IconData circleDown = IconDataRegular(0xf358);

  /// Alias arrow-alt-circle-down for icon [circleDown]
  @Deprecated('Use "circleDown" instead.')
  static const IconData arrowAltCircleDown = circleDown;

  /// Regular Circle Left icon
  ///
  /// https://fontawesome.com/icons/circle-left?style=regular
  /// arrow-circle-o-left, back, previous
  static const IconData circleLeft = IconDataRegular(0xf359);

  /// Alias arrow-alt-circle-left for icon [circleLeft]
  @Deprecated('Use "circleLeft" instead.')
  static const IconData arrowAltCircleLeft = circleLeft;

  /// Regular Circle Pause icon
  ///
  /// https://fontawesome.com/icons/circle-pause?style=regular
  /// hold, wait
  static const IconData circlePause = IconDataRegular(0xf28b);

  /// Alias pause-circle for icon [circlePause]
  @Deprecated('Use "circlePause" instead.')
  static const IconData pauseCircle = circlePause;

  /// Regular Circle Play icon
  ///
  /// https://fontawesome.com/icons/circle-play?style=regular
  /// audio, music, playing, sound, start, video
  static const IconData circlePlay = IconDataRegular(0xf144);

  /// Alias play-circle for icon [circlePlay]
  @Deprecated('Use "circlePlay" instead.')
  static const IconData playCircle = circlePlay;

  /// Regular Circle Question icon
  ///
  /// https://fontawesome.com/icons/circle-question?style=regular
  /// faq, help, information, support, unknown
  static const IconData circleQuestion = IconDataRegular(0xf059);

  /// Alias question-circle for icon [circleQuestion]
  @Deprecated('Use "circleQuestion" instead.')
  static const IconData questionCircle = circleQuestion;

  /// Regular Circle Right icon
  ///
  /// https://fontawesome.com/icons/circle-right?style=regular
  /// arrow-circle-o-right, forward, next
  static const IconData circleRight = IconDataRegular(0xf35a);

  /// Alias arrow-alt-circle-right for icon [circleRight]
  @Deprecated('Use "circleRight" instead.')
  static const IconData arrowAltCircleRight = circleRight;

  /// Regular Circle Stop icon
  ///
  /// https://fontawesome.com/icons/circle-stop?style=regular
  /// block, box, circle, square
  static const IconData circleStop = IconDataRegular(0xf28d);

  /// Alias stop-circle for icon [circleStop]
  @Deprecated('Use "circleStop" instead.')
  static const IconData stopCircle = circleStop;

  /// Regular Circle Up icon
  ///
  /// https://fontawesome.com/icons/circle-up?style=regular
  /// arrow-circle-o-up, upgrade
  static const IconData circleUp = IconDataRegular(0xf35b);

  /// Alias arrow-alt-circle-up for icon [circleUp]
  @Deprecated('Use "circleUp" instead.')
  static const IconData arrowAltCircleUp = circleUp;

  /// Regular Circle User icon
  ///
  /// https://fontawesome.com/icons/circle-user?style=regular
  /// employee, uer, username, users-people
  static const IconData circleUser = IconDataRegular(0xf2bd);

  /// Alias user-circle for icon [circleUser]
  @Deprecated('Use "circleUser" instead.')
  static const IconData userCircle = circleUser;

  /// Regular Circle Xmark icon
  ///
  /// https://fontawesome.com/icons/circle-xmark?style=regular
  /// close, cross, destroy, exit, incorrect, notice, notification, notify, problem, uncheck, wrong, x
  static const IconData circleXmark = IconDataRegular(0xf057);

  /// Alias times-circle for icon [circleXmark]
  @Deprecated('Use "circleXmark" instead.')
  static const IconData timesCircle = circleXmark;

  /// Alias xmark-circle for icon [circleXmark]
  @Deprecated('Use "circleXmark" instead.')
  static const IconData xmarkCircle = circleXmark;

  /// Regular Clipboard icon
  ///
  /// https://fontawesome.com/icons/clipboard?style=regular
  /// clipboar, clipboard, copy, notepad, notes, paste, record
  static const IconData clipboard = IconDataRegular(0xf328);

  /// Regular Clock icon
  ///
  /// https://fontawesome.com/icons/clock?style=regular
  /// 00, 4, 4:00, clock, date, four, four o’clock, hour, late, minute, o'clock, o’clock, pending, schedule, ticking, time, timer, timestamp, watch
  static const IconData clock = IconDataRegular(0xf017);

  /// Alias clock-four for icon [clock]
  @Deprecated('Use "clock" instead.')
  static const IconData clockFour = clock;

  /// Regular Clone icon
  ///
  /// https://fontawesome.com/icons/clone?style=regular
  /// arrange, copy, duplicate, paste
  static const IconData clone = IconDataRegular(0xf24d);

  /// Regular Closed Captioning icon
  ///
  /// https://fontawesome.com/icons/closed-captioning?style=regular
  /// cc, deaf, hearing, subtitle, subtitling, text, video
  static const IconData closedCaptioning = IconDataRegular(0xf20a);

  /// Regular Comment icon
  ///
  /// https://fontawesome.com/icons/comment?style=regular
  ///  conversation,  discussion,  talking, Right Speech Bubble, answer, bubble, chat, commenting, conversation, feedback, message, note, notification, sms, speech, talk, texting
  static const IconData comment = IconDataRegular(0xf075);

  /// Regular Comment Dots icon
  ///
  /// https://fontawesome.com/icons/comment-dots?style=regular
  /// answer, balloon, bubble, chat, comic, commenting, conversation, dialog, feedback, message, more, note, notification, reply, request, sms, speech, speech balloon, texting
  static const IconData commentDots = IconDataRegular(0xf4ad);

  /// Alias commenting for icon [commentDots]
  @Deprecated('Use "commentDots" instead.')
  static const IconData commenting = commentDots;

  /// Regular Comments icon
  ///
  /// https://fontawesome.com/icons/comments?style=regular
  ///  conversation,  discussion,  talking, Two Speech Bubbles, answer, bubble, chat, commenting, conversation, feedback, message, note, notification, sms, speech, talk, texting
  static const IconData comments = IconDataRegular(0xf086);

  /// Regular Compass icon
  ///
  /// https://fontawesome.com/icons/compass?style=regular
  /// compass, directions, directory, location, magnetic, menu, navigation, orienteering, safari, travel
  static const IconData compass = IconDataRegular(0xf14e);

  /// Regular Copy icon
  ///
  /// https://fontawesome.com/icons/copy?style=regular
  /// clone, duplicate, file, files-o, paper, paste
  static const IconData copy = IconDataRegular(0xf0c5);

  /// Regular Copyright icon
  ///
  /// https://fontawesome.com/icons/copyright?style=regular
  /// brand, c, copyright, mark, register, trademark
  static const IconData copyright = IconDataRegular(0xf1f9);

  /// Regular Credit Card icon
  ///
  /// https://fontawesome.com/icons/credit-card?style=regular
  /// buy, card, checkout, credit, credit card, credit-card-alt, debit, money, payment, purchase
  static const IconData creditCard = IconDataRegular(0xf09d);

  /// Alias credit-card-alt for icon [creditCard]
  @Deprecated('Use "creditCard" instead.')
  static const IconData creditCardAlt = creditCard;

  /// Regular Envelope icon
  ///
  /// https://fontawesome.com/icons/envelope?style=regular
  /// Back of Envelope, e-mail, email, envelope, letter, mail, message, newsletter, notification, offer, support
  static const IconData envelope = IconDataRegular(0xf0e0);

  /// Regular Envelope Open icon
  ///
  /// https://fontawesome.com/icons/envelope-open?style=regular
  /// e-mail, email, letter, mail, message, newsletter, notification, offer, support
  static const IconData envelopeOpen = IconDataRegular(0xf2b6);

  /// Regular Eye icon
  ///
  /// https://fontawesome.com/icons/eye?style=regular
  /// body, eye, look, optic, see, seen, show, sight, views, visible
  static const IconData eye = IconDataRegular(0xf06e);

  /// Regular Eye Slash icon
  ///
  /// https://fontawesome.com/icons/eye-slash?style=regular
  /// blind, disabled, hide, show, toggle, unseen, views, visible, visiblity
  static const IconData eyeSlash = IconDataRegular(0xf070);

  /// Regular Face Angry icon
  ///
  /// https://fontawesome.com/icons/face-angry?style=regular
  /// angry, angry face, disapprove, emoticon, face, mad, upset
  static const IconData faceAngry = IconDataRegular(0xf556);

  /// Alias angry for icon [faceAngry]
  @Deprecated('Use "faceAngry" instead.')
  static const IconData angry = faceAngry;

  /// Regular Face Dizzy icon
  ///
  /// https://fontawesome.com/icons/face-dizzy?style=regular
  /// dazed, dead, disapprove, emoticon, face
  static const IconData faceDizzy = IconDataRegular(0xf567);

  /// Alias dizzy for icon [faceDizzy]
  @Deprecated('Use "faceDizzy" instead.')
  static const IconData dizzy = faceDizzy;

  /// Regular Face Flushed icon
  ///
  /// https://fontawesome.com/icons/face-flushed?style=regular
  /// dazed, embarrassed, emoticon, face, flushed, flushed face
  static const IconData faceFlushed = IconDataRegular(0xf579);

  /// Alias flushed for icon [faceFlushed]
  @Deprecated('Use "faceFlushed" instead.')
  static const IconData flushed = faceFlushed;

  /// Regular Face Frown icon
  ///
  /// https://fontawesome.com/icons/face-frown?style=regular
  /// disapprove, emoticon, face, frown, frowning face, rating, sad, uer
  static const IconData faceFrown = IconDataRegular(0xf119);

  /// Alias frown for icon [faceFrown]
  @Deprecated('Use "faceFrown" instead.')
  static const IconData frown = faceFrown;

  /// Regular Face Frown Open icon
  ///
  /// https://fontawesome.com/icons/face-frown-open?style=regular
  /// disapprove, emoticon, face, frown, frowning face with open mouth, mouth, open, rating, sad
  static const IconData faceFrownOpen = IconDataRegular(0xf57a);

  /// Alias frown-open for icon [faceFrownOpen]
  @Deprecated('Use "faceFrownOpen" instead.')
  static const IconData frownOpen = faceFrownOpen;

  /// Regular Face Grimace icon
  ///
  /// https://fontawesome.com/icons/face-grimace?style=regular
  /// cringe, emoticon, face, grimace, grimacing face, teeth
  static const IconData faceGrimace = IconDataRegular(0xf57f);

  /// Alias grimace for icon [faceGrimace]
  @Deprecated('Use "faceGrimace" instead.')
  static const IconData grimace = faceGrimace;

  /// Regular Face Grin icon
  ///
  /// https://fontawesome.com/icons/face-grin?style=regular
  /// emoticon, face, grin, grinning face, laugh, smile
  static const IconData faceGrin = IconDataRegular(0xf580);

  /// Alias grin for icon [faceGrin]
  @Deprecated('Use "faceGrin" instead.')
  static const IconData grin = faceGrin;

  /// Regular Face Grin Beam icon
  ///
  /// https://fontawesome.com/icons/face-grin-beam?style=regular
  /// emoticon, eye, face, grinning face with smiling eyes, laugh, mouth, open, smile
  static const IconData faceGrinBeam = IconDataRegular(0xf582);

  /// Alias grin-beam for icon [faceGrinBeam]
  @Deprecated('Use "faceGrinBeam" instead.')
  static const IconData grinBeam = faceGrinBeam;

  /// Regular Face Grin Beam Sweat icon
  ///
  /// https://fontawesome.com/icons/face-grin-beam-sweat?style=regular
  /// cold, embarass, emoticon, face, grinning face with sweat, open, smile, sweat
  static const IconData faceGrinBeamSweat = IconDataRegular(0xf583);

  /// Alias grin-beam-sweat for icon [faceGrinBeamSweat]
  @Deprecated('Use "faceGrinBeamSweat" instead.')
  static const IconData grinBeamSweat = faceGrinBeamSweat;

  /// Regular Face Grin Hearts icon
  ///
  /// https://fontawesome.com/icons/face-grin-hearts?style=regular
  /// emoticon, eye, face, love, smile, smiling face with heart-eyes
  static const IconData faceGrinHearts = IconDataRegular(0xf584);

  /// Alias grin-hearts for icon [faceGrinHearts]
  @Deprecated('Use "faceGrinHearts" instead.')
  static const IconData grinHearts = faceGrinHearts;

  /// Regular Face Grin Squint icon
  ///
  /// https://fontawesome.com/icons/face-grin-squint?style=regular
  /// emoticon, face, grinning squinting face, laugh, mouth, satisfied, smile
  static const IconData faceGrinSquint = IconDataRegular(0xf585);

  /// Alias grin-squint for icon [faceGrinSquint]
  @Deprecated('Use "faceGrinSquint" instead.')
  static const IconData grinSquint = faceGrinSquint;

  /// Regular Face Grin Squint Tears icon
  ///
  /// https://fontawesome.com/icons/face-grin-squint-tears?style=regular
  /// emoticon, face, floor, happy, laugh, rolling, rolling on the floor laughing, smile
  static const IconData faceGrinSquintTears = IconDataRegular(0xf586);

  /// Alias grin-squint-tears for icon [faceGrinSquintTears]
  @Deprecated('Use "faceGrinSquintTears" instead.')
  static const IconData grinSquintTears = faceGrinSquintTears;

  /// Regular Face Grin Stars icon
  ///
  /// https://fontawesome.com/icons/face-grin-stars?style=regular
  /// emoticon, eyes, face, grinning, quality, star, star-struck, starry-eyed, vip
  static const IconData faceGrinStars = IconDataRegular(0xf587);

  /// Alias grin-stars for icon [faceGrinStars]
  @Deprecated('Use "faceGrinStars" instead.')
  static const IconData grinStars = faceGrinStars;

  /// Regular Face Grin Tears icon
  ///
  /// https://fontawesome.com/icons/face-grin-tears?style=regular
  /// LOL, emoticon, face, face with tears of joy, joy, laugh, tear
  static const IconData faceGrinTears = IconDataRegular(0xf588);

  /// Alias grin-tears for icon [faceGrinTears]
  @Deprecated('Use "faceGrinTears" instead.')
  static const IconData grinTears = faceGrinTears;

  /// Regular Face Grin Tongue icon
  ///
  /// https://fontawesome.com/icons/face-grin-tongue?style=regular
  /// LOL, emoticon, face, face with tongue, tongue
  static const IconData faceGrinTongue = IconDataRegular(0xf589);

  /// Alias grin-tongue for icon [faceGrinTongue]
  @Deprecated('Use "faceGrinTongue" instead.')
  static const IconData grinTongue = faceGrinTongue;

  /// Regular Face Grin Tongue Squint icon
  ///
  /// https://fontawesome.com/icons/face-grin-tongue-squint?style=regular
  /// LOL, emoticon, eye, face, horrible, squinting face with tongue, taste, tongue
  static const IconData faceGrinTongueSquint = IconDataRegular(0xf58a);

  /// Alias grin-tongue-squint for icon [faceGrinTongueSquint]
  @Deprecated('Use "faceGrinTongueSquint" instead.')
  static const IconData grinTongueSquint = faceGrinTongueSquint;

  /// Regular Face Grin Tongue Wink icon
  ///
  /// https://fontawesome.com/icons/face-grin-tongue-wink?style=regular
  /// LOL, emoticon, eye, face, joke, tongue, wink, winking face with tongue
  static const IconData faceGrinTongueWink = IconDataRegular(0xf58b);

  /// Alias grin-tongue-wink for icon [faceGrinTongueWink]
  @Deprecated('Use "faceGrinTongueWink" instead.')
  static const IconData grinTongueWink = faceGrinTongueWink;

  /// Regular Face Grin Wide icon
  ///
  /// https://fontawesome.com/icons/face-grin-wide?style=regular
  /// emoticon, face, grinning face with big eyes, laugh, mouth, open, smile
  static const IconData faceGrinWide = IconDataRegular(0xf581);

  /// Alias grin-alt for icon [faceGrinWide]
  @Deprecated('Use "faceGrinWide" instead.')
  static const IconData grinAlt = faceGrinWide;

  /// Regular Face Grin Wink icon
  ///
  /// https://fontawesome.com/icons/face-grin-wink?style=regular
  /// emoticon, face, flirt, laugh, smile
  static const IconData faceGrinWink = IconDataRegular(0xf58c);

  /// Alias grin-wink for icon [faceGrinWink]
  @Deprecated('Use "faceGrinWink" instead.')
  static const IconData grinWink = faceGrinWink;

  /// Regular Face Kiss icon
  ///
  /// https://fontawesome.com/icons/face-kiss?style=regular
  /// beso, emoticon, face, kiss, kissing face, love, smooch
  static const IconData faceKiss = IconDataRegular(0xf596);

  /// Alias kiss for icon [faceKiss]
  @Deprecated('Use "faceKiss" instead.')
  static const IconData kiss = faceKiss;

  /// Regular Face Kiss Beam icon
  ///
  /// https://fontawesome.com/icons/face-kiss-beam?style=regular
  /// beso, emoticon, eye, face, kiss, kissing face with smiling eyes, love, smile, smooch
  static const IconData faceKissBeam = IconDataRegular(0xf597);

  /// Alias kiss-beam for icon [faceKissBeam]
  @Deprecated('Use "faceKissBeam" instead.')
  static const IconData kissBeam = faceKissBeam;

  /// Regular Face Kiss Wink Heart icon
  ///
  /// https://fontawesome.com/icons/face-kiss-wink-heart?style=regular
  /// beso, emoticon, face, face blowing a kiss, kiss, love, smooch
  static const IconData faceKissWinkHeart = IconDataRegular(0xf598);

  /// Alias kiss-wink-heart for icon [faceKissWinkHeart]
  @Deprecated('Use "faceKissWinkHeart" instead.')
  static const IconData kissWinkHeart = faceKissWinkHeart;

  /// Regular Face Laugh icon
  ///
  /// https://fontawesome.com/icons/face-laugh?style=regular
  /// LOL, emoticon, face, laugh, smile
  static const IconData faceLaugh = IconDataRegular(0xf599);

  /// Alias laugh for icon [faceLaugh]
  @Deprecated('Use "faceLaugh" instead.')
  static const IconData laugh = faceLaugh;

  /// Regular Face Laugh Beam icon
  ///
  /// https://fontawesome.com/icons/face-laugh-beam?style=regular
  /// LOL, beaming face with smiling eyes, emoticon, eye, face, grin, happy, smile
  static const IconData faceLaughBeam = IconDataRegular(0xf59a);

  /// Alias laugh-beam for icon [faceLaughBeam]
  @Deprecated('Use "faceLaughBeam" instead.')
  static const IconData laughBeam = faceLaughBeam;

  /// Regular Face Laugh Squint icon
  ///
  /// https://fontawesome.com/icons/face-laugh-squint?style=regular
  /// LOL, emoticon, face, happy, smile
  static const IconData faceLaughSquint = IconDataRegular(0xf59b);

  /// Alias laugh-squint for icon [faceLaughSquint]
  @Deprecated('Use "faceLaughSquint" instead.')
  static const IconData laughSquint = faceLaughSquint;

  /// Regular Face Laugh Wink icon
  ///
  /// https://fontawesome.com/icons/face-laugh-wink?style=regular
  /// LOL, emoticon, face, happy, smile
  static const IconData faceLaughWink = IconDataRegular(0xf59c);

  /// Alias laugh-wink for icon [faceLaughWink]
  @Deprecated('Use "faceLaughWink" instead.')
  static const IconData laughWink = faceLaughWink;

  /// Regular Face Meh icon
  ///
  /// https://fontawesome.com/icons/face-meh?style=regular
  /// deadpan, default, emoticon, face, meh, neutral, neutral face, rating, uer
  static const IconData faceMeh = IconDataRegular(0xf11a);

  /// Alias meh for icon [faceMeh]
  @Deprecated('Use "faceMeh" instead.')
  static const IconData meh = faceMeh;

  /// Regular Face Meh Blank icon
  ///
  /// https://fontawesome.com/icons/face-meh-blank?style=regular
  /// emoticon, face, face without mouth, mouth, neutral, quiet, rating, silent
  static const IconData faceMehBlank = IconDataRegular(0xf5a4);

  /// Alias meh-blank for icon [faceMehBlank]
  @Deprecated('Use "faceMehBlank" instead.')
  static const IconData mehBlank = faceMehBlank;

  /// Regular Face Rolling Eyes icon
  ///
  /// https://fontawesome.com/icons/face-rolling-eyes?style=regular
  /// emoticon, eyeroll, eyes, face, face with rolling eyes, neutral, rating, rolling
  static const IconData faceRollingEyes = IconDataRegular(0xf5a5);

  /// Alias meh-rolling-eyes for icon [faceRollingEyes]
  @Deprecated('Use "faceRollingEyes" instead.')
  static const IconData mehRollingEyes = faceRollingEyes;

  /// Regular Face Sad Cry icon
  ///
  /// https://fontawesome.com/icons/face-sad-cry?style=regular
  /// cry, emoticon, face, loudly crying face, sad, sob, tear, tears
  static const IconData faceSadCry = IconDataRegular(0xf5b3);

  /// Alias sad-cry for icon [faceSadCry]
  @Deprecated('Use "faceSadCry" instead.')
  static const IconData sadCry = faceSadCry;

  /// Regular Face Sad Tear icon
  ///
  /// https://fontawesome.com/icons/face-sad-tear?style=regular
  /// cry, crying face, emoticon, face, sad, tear, tears
  static const IconData faceSadTear = IconDataRegular(0xf5b4);

  /// Alias sad-tear for icon [faceSadTear]
  @Deprecated('Use "faceSadTear" instead.')
  static const IconData sadTear = faceSadTear;

  /// Regular Face Smile icon
  ///
  /// https://fontawesome.com/icons/face-smile?style=regular
  /// approve, default, emoticon, face, happy, rating, satisfied, slightly smiling face, smile, uer
  static const IconData faceSmile = IconDataRegular(0xf118);

  /// Alias smile for icon [faceSmile]
  @Deprecated('Use "faceSmile" instead.')
  static const IconData smile = faceSmile;

  /// Regular Face Smile Beam icon
  ///
  /// https://fontawesome.com/icons/face-smile-beam?style=regular
  /// blush, emoticon, eye, face, happy, positive, smile, smiling face with smiling eyes
  static const IconData faceSmileBeam = IconDataRegular(0xf5b8);

  /// Alias smile-beam for icon [faceSmileBeam]
  @Deprecated('Use "faceSmileBeam" instead.')
  static const IconData smileBeam = faceSmileBeam;

  /// Regular Face Smile Wink icon
  ///
  /// https://fontawesome.com/icons/face-smile-wink?style=regular
  /// emoticon, face, happy, hint, joke, wink, winking face
  static const IconData faceSmileWink = IconDataRegular(0xf4da);

  /// Alias smile-wink for icon [faceSmileWink]
  @Deprecated('Use "faceSmileWink" instead.')
  static const IconData smileWink = faceSmileWink;

  /// Regular Face Surprise icon
  ///
  /// https://fontawesome.com/icons/face-surprise?style=regular
  /// emoticon, face, face with open mouth, mouth, open, shocked, sympathy
  static const IconData faceSurprise = IconDataRegular(0xf5c2);

  /// Alias surprise for icon [faceSurprise]
  @Deprecated('Use "faceSurprise" instead.')
  static const IconData surprise = faceSurprise;

  /// Regular Face Tired icon
  ///
  /// https://fontawesome.com/icons/face-tired?style=regular
  /// angry, emoticon, face, grumpy, tired, tired face, upset
  static const IconData faceTired = IconDataRegular(0xf5c8);

  /// Alias tired for icon [faceTired]
  @Deprecated('Use "faceTired" instead.')
  static const IconData tired = faceTired;

  /// Regular File icon
  ///
  /// https://fontawesome.com/icons/file?style=regular
  /// Empty Document, cv, document, new, page, page facing up, pdf, resume
  static const IconData file = IconDataRegular(0xf15b);

  /// Regular File Audio icon
  ///
  /// https://fontawesome.com/icons/file-audio?style=regular
  /// document, mp3, music, page, play, sound
  static const IconData fileAudio = IconDataRegular(0xf1c7);

  /// Regular File Code icon
  ///
  /// https://fontawesome.com/icons/file-code?style=regular
  /// css, development, document, html, mysql, sql
  static const IconData fileCode = IconDataRegular(0xf1c9);

  /// Regular File Excel icon
  ///
  /// https://fontawesome.com/icons/file-excel?style=regular
  /// csv, document, numbers, spreadsheets, table
  static const IconData fileExcel = IconDataRegular(0xf1c3);

  /// Regular File Image icon
  ///
  /// https://fontawesome.com/icons/file-image?style=regular
  /// Document with Picture, document, image, img, jpg, photo, png
  static const IconData fileImage = IconDataRegular(0xf1c5);

  /// Regular File Lines icon
  ///
  /// https://fontawesome.com/icons/file-lines?style=regular
  /// Document, Document with Text, document, file-text, invoice, new, page, pdf
  static const IconData fileLines = IconDataRegular(0xf15c);

  /// Alias file-alt for icon [fileLines]
  @Deprecated('Use "fileLines" instead.')
  static const IconData fileAlt = fileLines;

  /// Alias file-text for icon [fileLines]
  @Deprecated('Use "fileLines" instead.')
  static const IconData fileText = fileLines;

  /// Regular File Pdf icon
  ///
  /// https://fontawesome.com/icons/file-pdf?style=regular
  /// acrobat, document, preview, save
  static const IconData filePdf = IconDataRegular(0xf1c1);

  /// Regular File Powerpoint icon
  ///
  /// https://fontawesome.com/icons/file-powerpoint?style=regular
  /// display, document, keynote, presentation
  static const IconData filePowerpoint = IconDataRegular(0xf1c4);

  /// Regular File Video icon
  ///
  /// https://fontawesome.com/icons/file-video?style=regular
  /// document, m4v, movie, mp4, play
  static const IconData fileVideo = IconDataRegular(0xf1c8);

  /// Regular File Word icon
  ///
  /// https://fontawesome.com/icons/file-word?style=regular
  /// document, edit, page, text, writing
  static const IconData fileWord = IconDataRegular(0xf1c2);

  /// Regular File Zipper icon
  ///
  /// https://fontawesome.com/icons/file-zipper?style=regular
  /// .zip, bundle, compress, compression, download, zip
  static const IconData fileZipper = IconDataRegular(0xf1c6);

  /// Alias file-archive for icon [fileZipper]
  @Deprecated('Use "fileZipper" instead.')
  static const IconData fileArchive = fileZipper;

  /// Regular Flag icon
  ///
  /// https://fontawesome.com/icons/flag?style=regular
  /// black flag, country, notice, notification, notify, pole, report, symbol, waving
  static const IconData flag = IconDataRegular(0xf024);

  /// Regular Floppy Disk icon
  ///
  /// https://fontawesome.com/icons/floppy-disk?style=regular
  /// Black Hard Shell Floppy Disk, computer, disk, download, floppy, floppy disk, floppy-o
  static const IconData floppyDisk = IconDataRegular(0xf0c7);

  /// Alias save for icon [floppyDisk]
  @Deprecated('Use "floppyDisk" instead.')
  static const IconData save = floppyDisk;

  /// Regular Folder icon
  ///
  /// https://fontawesome.com/icons/folder?style=regular
  /// Black Folder, archive, directory, document, file, file folder, folder
  static const IconData folder = IconDataRegular(0xf07b);

  /// Alias folder-blank for icon [folder]
  @Deprecated('Use "folder" instead.')
  static const IconData folderBlank = folder;

  /// Regular Folder Closed icon
  ///
  /// https://fontawesome.com/icons/folder-closed?style=regular
  /// file
  static const IconData folderClosed = IconDataRegular(0xe185);

  /// Regular Folder Open icon
  ///
  /// https://fontawesome.com/icons/folder-open?style=regular
  /// Open Folder, archive, directory, document, empty, file, folder, new, open, open file folder
  static const IconData folderOpen = IconDataRegular(0xf07c);

  /// Regular Font Awesome icon
  ///
  /// https://fontawesome.com/icons/font-awesome?style=regular
  /// awesome, flag, font, icons, typeface
  static const IconData fontAwesome = IconDataRegular(0xf2b4);

  /// Alias font-awesome-flag for icon [fontAwesome]
  @Deprecated('Use "fontAwesome" instead.')
  static const IconData fontAwesomeFlag = fontAwesome;

  /// Alias font-awesome-logo-full for icon [fontAwesome]
  @Deprecated('Use "fontAwesome" instead.')
  static const IconData fontAwesomeLogoFull = fontAwesome;

  /// Regular Futbol icon
  ///
  /// https://fontawesome.com/icons/futbol?style=regular
  /// ball, football, mls, soccer, soccer ball
  static const IconData futbol = IconDataRegular(0xf1e3);

  /// Alias futbol-ball for icon [futbol]
  @Deprecated('Use "futbol" instead.')
  static const IconData futbolBall = futbol;

  /// Alias soccer-ball for icon [futbol]
  @Deprecated('Use "futbol" instead.')
  static const IconData soccerBall = futbol;

  /// Regular Gem icon
  ///
  /// https://fontawesome.com/icons/gem?style=regular
  /// diamond, gem, gem stone, jewel, jewelry, sapphire, stone, treasure
  static const IconData gem = IconDataRegular(0xf3a5);

  /// Regular Hand icon
  ///
  /// https://fontawesome.com/icons/hand?style=regular
  /// Raised Hand, backhand, game, halt, palm, raised, raised back of hand, request, roshambo, stop
  static const IconData hand = IconDataRegular(0xf256);

  /// Alias hand-paper for icon [hand]
  @Deprecated('Use "hand" instead.')
  static const IconData handPaper = hand;

  /// Regular Hand Back Fist icon
  ///
  /// https://fontawesome.com/icons/hand-back-fist?style=regular
  /// fist, game, roshambo
  static const IconData handBackFist = IconDataRegular(0xf255);

  /// Alias hand-rock for icon [handBackFist]
  @Deprecated('Use "handBackFist" instead.')
  static const IconData handRock = handBackFist;

  /// Regular Hand Lizard icon
  ///
  /// https://fontawesome.com/icons/hand-lizard?style=regular
  /// game, roshambo
  static const IconData handLizard = IconDataRegular(0xf258);

  /// Regular Hand Peace icon
  ///
  /// https://fontawesome.com/icons/hand-peace?style=regular
  /// hand, rest, truce, v, victory, victory hand
  static const IconData handPeace = IconDataRegular(0xf25b);

  /// Regular Hand Point Down icon
  ///
  /// https://fontawesome.com/icons/hand-point-down?style=regular
  /// finger, hand-o-down, point
  static const IconData handPointDown = IconDataRegular(0xf0a7);

  /// Regular Hand Point Left icon
  ///
  /// https://fontawesome.com/icons/hand-point-left?style=regular
  /// back, finger, hand-o-left, left, point, previous
  static const IconData handPointLeft = IconDataRegular(0xf0a5);

  /// Regular Hand Point Right icon
  ///
  /// https://fontawesome.com/icons/hand-point-right?style=regular
  /// finger, forward, hand-o-right, next, point, right
  static const IconData handPointRight = IconDataRegular(0xf0a4);

  /// Regular Hand Point Up icon
  ///
  /// https://fontawesome.com/icons/hand-point-up?style=regular
  /// finger, hand, hand-o-up, index, index pointing up, point, request, up, upgrade
  static const IconData handPointUp = IconDataRegular(0xf0a6);

  /// Regular Hand Pointer icon
  ///
  /// https://fontawesome.com/icons/hand-pointer?style=regular
  /// arrow, cursor, select
  static const IconData handPointer = IconDataRegular(0xf25a);

  /// Regular Hand Scissors icon
  ///
  /// https://fontawesome.com/icons/hand-scissors?style=regular
  /// cut, game, roshambo
  static const IconData handScissors = IconDataRegular(0xf257);

  /// Regular Hand Spock icon
  ///
  /// https://fontawesome.com/icons/hand-spock?style=regular
  /// finger, hand, live long, palm, prosper, salute, spock, star trek, vulcan, vulcan salute
  static const IconData handSpock = IconDataRegular(0xf259);

  /// Regular Handshake icon
  ///
  /// https://fontawesome.com/icons/handshake?style=regular
  /// agreement, greeting, meeting, partnership
  static const IconData handshake = IconDataRegular(0xf2b5);

  /// Regular Hard Drive icon
  ///
  /// https://fontawesome.com/icons/hard-drive?style=regular
  /// Hard Disk, cpu, hard drive, harddrive, machine, save, storage
  static const IconData hardDrive = IconDataRegular(0xf0a0);

  /// Alias hdd for icon [hardDrive]
  @Deprecated('Use "hardDrive" instead.')
  static const IconData hdd = hardDrive;

  /// Regular Heart icon
  ///
  /// https://fontawesome.com/icons/heart?style=regular
  /// ace, black, black heart, blue, blue heart, brown, brown heart, card, evil, favorite, game, green, green heart, heart, heart suit, like, love, orange, orange heart, purple, purple heart, red heart, relationship, valentine, white, white heart, wicked, wishlist, yellow, yellow heart
  static const IconData heart = IconDataRegular(0xf004);

  /// Regular Hospital icon
  ///
  /// https://fontawesome.com/icons/hospital?style=regular
  /// building, covid-19, doctor, emergency room, hospital, medical center, medicine
  static const IconData hospital = IconDataRegular(0xf0f8);

  /// Alias hospital-alt for icon [hospital]
  @Deprecated('Use "hospital" instead.')
  static const IconData hospitalAlt = hospital;

  /// Alias hospital-wide for icon [hospital]
  @Deprecated('Use "hospital" instead.')
  static const IconData hospitalWide = hospital;

  /// Regular Hourglass icon
  ///
  /// https://fontawesome.com/icons/hourglass?style=regular
  /// hour, hourglass, hourglass not done, minute, sand, stopwatch, time, timer
  static const IconData hourglass = IconDataRegular(0xf254);

  /// Alias hourglass-empty for icon [hourglass]
  @Deprecated('Use "hourglass" instead.')
  static const IconData hourglassEmpty = hourglass;

  /// Regular Hourglass Half icon
  ///
  /// https://fontawesome.com/icons/hourglass-half?style=regular
  /// hour, minute, pending, sand, stopwatch, time, waiting
  static const IconData hourglassHalf = IconDataRegular(0xf252);

  /// Alias hourglass-2 for icon [hourglassHalf]
  @Deprecated('Use "hourglassHalf" instead.')
  static const IconData hourglass2 = hourglassHalf;

  /// Regular Id Badge icon
  ///
  /// https://fontawesome.com/icons/id-badge?style=regular
  /// address, contact, identification, license, profile, uer, username
  static const IconData idBadge = IconDataRegular(0xf2c1);

  /// Regular Id Card icon
  ///
  /// https://fontawesome.com/icons/id-card?style=regular
  /// contact, demographics, document, identification, issued, profile, registration, uer, username
  static const IconData idCard = IconDataRegular(0xf2c2);

  /// Alias drivers-license for icon [idCard]
  @Deprecated('Use "idCard" instead.')
  static const IconData driversLicense = idCard;

  /// Regular Image icon
  ///
  /// https://fontawesome.com/icons/image?style=regular
  /// album, img, landscape, photo, picture
  static const IconData image = IconDataRegular(0xf03e);

  /// Regular Images icon
  ///
  /// https://fontawesome.com/icons/images?style=regular
  /// album, img, landscape, photo, picture
  static const IconData images = IconDataRegular(0xf302);

  /// Regular Keyboard icon
  ///
  /// https://fontawesome.com/icons/keyboard?style=regular
  /// accessory, computer, edit, input, keyboard, text, type, write
  static const IconData keyboard = IconDataRegular(0xf11c);

  /// Regular Lemon icon
  ///
  /// https://fontawesome.com/icons/lemon?style=regular
  /// citrus, fruit, lemon, lemonade, lime, tart
  static const IconData lemon = IconDataRegular(0xf094);

  /// Regular Life Ring icon
  ///
  /// https://fontawesome.com/icons/life-ring?style=regular
  /// coast guard, help, overboard, save, support
  static const IconData lifeRing = IconDataRegular(0xf1cd);

  /// Regular Lightbulb icon
  ///
  /// https://fontawesome.com/icons/lightbulb?style=regular
  ///   comic,   electric,   idea,   innovation,   inspiration,   light,   light bulb,  bulb, bulb, comic, electric, energy, idea, inspiration, mechanical
  static const IconData lightbulb = IconDataRegular(0xf0eb);

  /// Regular Map icon
  ///
  /// https://fontawesome.com/icons/map?style=regular
  /// address, coordinates, destination, gps, localize, location, map, navigation, paper, pin, place, point of interest, position, route, travel, world, world map
  static const IconData map = IconDataRegular(0xf279);

  /// Regular Message icon
  ///
  /// https://fontawesome.com/icons/message?style=regular
  ///  conversation,  discussion,  talking, answer, bubble, chat, commenting, conversation, feedback, message, note, notification, sms, speech, talk, texting
  static const IconData message = IconDataRegular(0xf27a);

  /// Alias comment-alt for icon [message]
  @Deprecated('Use "message" instead.')
  static const IconData commentAlt = message;

  /// Regular Money Bill 1 icon
  ///
  /// https://fontawesome.com/icons/money-bill-1?style=regular
  /// buy, cash, checkout, money, payment, premium, price, purchase, salary
  static const IconData moneyBill1 = IconDataRegular(0xf3d1);

  /// Alias money-bill-alt for icon [moneyBill1]
  @Deprecated('Use "moneyBill1" instead.')
  static const IconData moneyBillAlt = moneyBill1;

  /// Regular Moon icon
  ///
  /// https://fontawesome.com/icons/moon?style=regular
  /// Power Sleep Symbol, contrast, crescent, crescent moon, dark, lunar, moon, night
  static const IconData moon = IconDataRegular(0xf186);

  /// Regular Newspaper icon
  ///
  /// https://fontawesome.com/icons/newspaper?style=regular
  /// article, editorial, headline, journal, journalism, news, newsletter, newspaper, paper, press
  static const IconData newspaper = IconDataRegular(0xf1ea);

  /// Regular Note Sticky icon
  ///
  /// https://fontawesome.com/icons/note-sticky?style=regular
  /// message, note, paper, reminder, sticker
  static const IconData noteSticky = IconDataRegular(0xf249);

  /// Alias sticky-note for icon [noteSticky]
  @Deprecated('Use "noteSticky" instead.')
  static const IconData stickyNote = noteSticky;

  /// Regular Object Group icon
  ///
  /// https://fontawesome.com/icons/object-group?style=regular
  /// combine, copy, design, merge, select
  static const IconData objectGroup = IconDataRegular(0xf247);

  /// Regular Object Ungroup icon
  ///
  /// https://fontawesome.com/icons/object-ungroup?style=regular
  /// copy, design, merge, select, separate
  static const IconData objectUngroup = IconDataRegular(0xf248);

  /// Regular Paper Plane icon
  ///
  /// https://fontawesome.com/icons/paper-plane?style=regular
  /// air, float, fold, mail, paper, send
  static const IconData paperPlane = IconDataRegular(0xf1d8);

  /// Regular Paste icon
  ///
  /// https://fontawesome.com/icons/paste?style=regular
  /// clipboard, copy, document, paper
  static const IconData paste = IconDataRegular(0xf0ea);

  /// Alias file-clipboard for icon [paste]
  @Deprecated('Use "paste" instead.')
  static const IconData fileClipboard = paste;

  /// Regular Pen To Square icon
  ///
  /// https://fontawesome.com/icons/pen-to-square?style=regular
  /// edit, modify, pen, pencil, update, write
  static const IconData penToSquare = IconDataRegular(0xf044);

  /// Alias edit for icon [penToSquare]
  @Deprecated('Use "penToSquare" instead.')
  static const IconData edit = penToSquare;

  /// Regular Rectangle List icon
  ///
  /// https://fontawesome.com/icons/rectangle-list?style=regular
  /// cheatsheet, checklist, completed, done, finished, ol, summary, todo, ul
  static const IconData rectangleList = IconDataRegular(0xf022);

  /// Alias list-alt for icon [rectangleList]
  @Deprecated('Use "rectangleList" instead.')
  static const IconData listAlt = rectangleList;

  /// Regular Rectangle Xmark icon
  ///
  /// https://fontawesome.com/icons/rectangle-xmark?style=regular
  /// browser, cancel, computer, development, uncheck
  static const IconData rectangleXmark = IconDataRegular(0xf410);

  /// Alias rectangle-times for icon [rectangleXmark]
  @Deprecated('Use "rectangleXmark" instead.')
  static const IconData rectangleTimes = rectangleXmark;

  /// Alias times-rectangle for icon [rectangleXmark]
  @Deprecated('Use "rectangleXmark" instead.')
  static const IconData timesRectangle = rectangleXmark;

  /// Alias window-close for icon [rectangleXmark]
  @Deprecated('Use "rectangleXmark" instead.')
  static const IconData windowClose = rectangleXmark;

  /// Regular Registered icon
  ///
  /// https://fontawesome.com/icons/registered?style=regular
  /// copyright, mark, r, registered, trademark
  static const IconData registered = IconDataRegular(0xf25d);

  /// Regular Share From Square icon
  ///
  /// https://fontawesome.com/icons/share-from-square?style=regular
  /// forward, save, send, social
  static const IconData shareFromSquare = IconDataRegular(0xf14d);

  /// Alias share-square for icon [shareFromSquare]
  @Deprecated('Use "shareFromSquare" instead.')
  static const IconData shareSquare = shareFromSquare;

  /// Regular Snowflake icon
  ///
  /// https://fontawesome.com/icons/snowflake?style=regular
  /// Heavy Chevron Snowflake, cold, precipitation, rain, snow, snowfall, snowflake, winter
  static const IconData snowflake = IconDataRegular(0xf2dc);

  /// Regular Square icon
  ///
  /// https://fontawesome.com/icons/square?style=regular
  /// Black Square, black medium square, block, box, geometric, shape, square, white medium square
  static const IconData square = IconDataRegular(0xf0c8);

  /// Regular Square Caret Down icon
  ///
  /// https://fontawesome.com/icons/square-caret-down?style=regular
  /// arrow, caret-square-o-down, dropdown, expand, insert, menu, more, triangle
  static const IconData squareCaretDown = IconDataRegular(0xf150);

  /// Alias caret-square-down for icon [squareCaretDown]
  @Deprecated('Use "squareCaretDown" instead.')
  static const IconData caretSquareDown = squareCaretDown;

  /// Regular Square Caret Left icon
  ///
  /// https://fontawesome.com/icons/square-caret-left?style=regular
  /// arrow, back, caret-square-o-left, previous, triangle
  static const IconData squareCaretLeft = IconDataRegular(0xf191);

  /// Alias caret-square-left for icon [squareCaretLeft]
  @Deprecated('Use "squareCaretLeft" instead.')
  static const IconData caretSquareLeft = squareCaretLeft;

  /// Regular Square Caret Right icon
  ///
  /// https://fontawesome.com/icons/square-caret-right?style=regular
  /// arrow, caret-square-o-right, forward, next, triangle
  static const IconData squareCaretRight = IconDataRegular(0xf152);

  /// Alias caret-square-right for icon [squareCaretRight]
  @Deprecated('Use "squareCaretRight" instead.')
  static const IconData caretSquareRight = squareCaretRight;

  /// Regular Square Caret Up icon
  ///
  /// https://fontawesome.com/icons/square-caret-up?style=regular
  /// arrow, caret-square-o-up, collapse, triangle, upgrade, upload
  static const IconData squareCaretUp = IconDataRegular(0xf151);

  /// Alias caret-square-up for icon [squareCaretUp]
  @Deprecated('Use "squareCaretUp" instead.')
  static const IconData caretSquareUp = squareCaretUp;

  /// Regular Square Check icon
  ///
  /// https://fontawesome.com/icons/square-check?style=regular
  /// accept, agree, box, button, check, check box with check, check mark button, checkmark, confirm, correct, coupon, done, enable, mark, ok, select, success, tick, todo, validate, working, yes, ✓
  static const IconData squareCheck = IconDataRegular(0xf14a);

  /// Alias check-square for icon [squareCheck]
  @Deprecated('Use "squareCheck" instead.')
  static const IconData checkSquare = squareCheck;

  /// Regular Square Full icon
  ///
  /// https://fontawesome.com/icons/square-full?style=regular
  /// black large square, block, blue, blue square, box, brown, brown square, geometric, green, green square, orange, orange square, purple, purple square, red, red square, shape, square, white large square, yellow, yellow square
  static const IconData squareFull = IconDataRegular(0xf45c);

  /// Regular Square Minus icon
  ///
  /// https://fontawesome.com/icons/square-minus?style=regular
  /// collapse, delete, hide, minify, negative, remove, shape, trash
  static const IconData squareMinus = IconDataRegular(0xf146);

  /// Alias minus-square for icon [squareMinus]
  @Deprecated('Use "squareMinus" instead.')
  static const IconData minusSquare = squareMinus;

  /// Regular Square Plus icon
  ///
  /// https://fontawesome.com/icons/square-plus?style=regular
  /// add, create, expand, new, positive, shape
  static const IconData squarePlus = IconDataRegular(0xf0fe);

  /// Alias plus-square for icon [squarePlus]
  @Deprecated('Use "squarePlus" instead.')
  static const IconData plusSquare = squarePlus;

  /// Regular Star icon
  ///
  /// https://fontawesome.com/icons/star?style=regular
  /// achievement, award, favorite, important, night, quality, rating, score, star, vip
  static const IconData star = IconDataRegular(0xf005);

  /// Regular Star Half icon
  ///
  /// https://fontawesome.com/icons/star-half?style=regular
  /// achievement, award, rating, score, star-half-empty, star-half-full
  static const IconData starHalf = IconDataRegular(0xf089);

  /// Regular Star Half Stroke icon
  ///
  /// https://fontawesome.com/icons/star-half-stroke?style=regular
  /// achievement, award, rating, score, star-half-empty, star-half-full
  static const IconData starHalfStroke = IconDataRegular(0xf5c0);

  /// Alias star-half-alt for icon [starHalfStroke]
  @Deprecated('Use "starHalfStroke" instead.')
  static const IconData starHalfAlt = starHalfStroke;

  /// Regular Sun icon
  ///
  /// https://fontawesome.com/icons/sun?style=regular
  /// bright, brighten, contrast, day, lighter, rays, sol, solar, star, sun, sunny, weather
  static const IconData sun = IconDataRegular(0xf185);

  /// Regular Thumbs Down icon
  ///
  /// https://fontawesome.com/icons/thumbs-down?style=regular
  /// -1, disagree, disapprove, dislike, down, hand, social, thumb, thumbs down, thumbs-o-down
  static const IconData thumbsDown = IconDataRegular(0xf165);

  /// Regular Thumbs Up icon
  ///
  /// https://fontawesome.com/icons/thumbs-up?style=regular
  /// +1, agree, approve, favorite, hand, like, ok, okay, social, success, thumb, thumbs up, thumbs-o-up, up, yes, you got it dude
  static const IconData thumbsUp = IconDataRegular(0xf164);

  /// Regular Trash Can icon
  ///
  /// https://fontawesome.com/icons/trash-can?style=regular
  /// delete, garbage, hide, remove, trash-o
  static const IconData trashCan = IconDataRegular(0xf2ed);

  /// Alias trash-alt for icon [trashCan]
  @Deprecated('Use "trashCan" instead.')
  static const IconData trashAlt = trashCan;

  /// Regular User icon
  ///
  /// https://fontawesome.com/icons/user?style=regular
  /// adult, bust, bust in silhouette, default, employee, gender-neutral, person, profile, silhouette, uer, unspecified gender, username, users-people
  static const IconData user = IconDataRegular(0xf007);

  /// Regular Window Maximize icon
  ///
  /// https://fontawesome.com/icons/window-maximize?style=regular
  /// Maximize, browser, computer, development, expand
  static const IconData windowMaximize = IconDataRegular(0xf2d0);

  /// Regular Window Minimize icon
  ///
  /// https://fontawesome.com/icons/window-minimize?style=regular
  /// Minimize, browser, collapse, computer, development
  static const IconData windowMinimize = IconDataRegular(0xf2d1);

  /// Regular Window Restore icon
  ///
  /// https://fontawesome.com/icons/window-restore?style=regular
  /// browser, computer, development
  static const IconData windowRestore = IconDataRegular(0xf2d2);
}
